### ISSUE TITLE
能给个c++调用的demo吗？qml的不怎么用，不大明白

### ISSUE THREAD

**Issue by peter-wwj** [188080501/JQQmlImage#14]
能给个c++调用的demo吗？qml的不怎么用，不大明白

**Comment by 188080501** [comment]
这个是给QML写的，C++那里不能用

**Comment by 188080501** [comment]
另外使用的话，就是在这里：
https://github.com/188080501/JQQmlImage/blob/master/qml/main.qml

你就当成普通的Image，把source改成cacheImageSource即可

**Comment by peter-wwj** [comment]
我这边需要用c++ 结合opengl做窗口渲染，qml可能用处不大，谢谢，可以尝试封装成C++版本使用的库

**Comment by 188080501** [comment]
目前版本（V1.1）中，已经在C++中提供了接口
QImage保存到jqic数据：
JQQmlImageManage::imageToJqicData

jqic数据解析道QImage
JQQmlImageManage::jqicDataToImage

jqic数据的保存需要手写
