### ISSUE TITLE
测试QML里面的图片路径可不可以改成相对路径呢

### ISSUE THREAD

**Issue by matengxiao** [188080501/JQQmlImage#4]
测试QML里面的图片路径可不可以改成相对路径呢，另外这个最低支持到那个Qt版本呢

**Comment by 188080501** [comment]
主要是C++那里用了C++11的语法，这样子的话是要编译器支持C++11才可以
Qt的话，我建议是5.5以后的版本

**Comment by 188080501** [comment]
相对路径支持，这个我去加下

**Comment by 188080501** [comment]
已经修改好并且合并到了master分支
